## **Arithmetic**

In [1]:
3 + 4

7

In [2]:
3 - 4

-1

In [3]:
3 * 4

12

In [4]:
3 / 4

0.75

In [5]:
(2 + 3) * 4 / (2 - 3)

-20.0

## **Variables and Assignments**

In [6]:
a = 3
b = 4
c = 3.0
d = 3 + 2j
e = "string"

In [7]:
print (a)
print (a, b, c)
print (d)
print (e)

3
3 4 3.0
(3+2j)
string


In [8]:
print (a + b)
print (a - b)
print (a * b)
print (a / b)

7
-1
12
0.75


## **Logical Expression**

In [9]:
a = 3
b = -3
c = 3

In [10]:
a == b

False

In [11]:
 a != b

True

In [12]:
a > b

True

In [13]:
a < b

False

In [14]:
a <= b

False

In [15]:
(a == b) or (a > b)

True

In [16]:
(a !=b) and (a < b)

False

## **Lists and Tuples**

Python has two data structures, lists and tuples, that consist of a list of one or more elements. The elements of lists or tuples can be numbers or strings, or both. 

Lists are defined by a pair of square brackets on either end with individual elements separated by commas

In [17]:
al = [1, 2, 3]
bl = ["a", "b", 'c']
cl = [1, 2, 3, "a", "b", 'c']
print (al, bl, cl)

[1, 2, 3] ['a', 'b', 'c'] [1, 2, 3, 'a', 'b', 'c']


Tuples are lists that are immutable. That is, once defined, the individual elements of a tuple cannot be changed. Whereas a list is written as a sequence of numbers enclosed in square brackets, a tuple is written as a sequence of numbers enclosed in round parentheses.

In [18]:
at = (1, 2, 3)
bt = ("a", "b", 'c')
ct = (1, 2, 3, "a", "b", 'c')
print (at, bt, ct)

(1, 2, 3) ('a', 'b', 'c') (1, 2, 3, 'a', 'b', 'c')


In [19]:
print (al[0])

1


In [20]:
print (at[0])

1


In [21]:
al[0] = 5
print (al)

[5, 2, 3]


In [22]:
at[0] = 5

TypeError: 'tuple' object does not support item assignment

In [23]:
al + 2
al * 2.

TypeError: can only concatenate list (not "int") to list

In [24]:
at / 2

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

## **Arrays**

Python does not have built-in support for Arrays, but Python Lists can be used instead.

In [25]:
aa = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print (aa)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [26]:
aa[0]

[1, 2, 3]

In [27]:
aa[0][1]

2

The NumPy array is the real workhorse of data structures for scientific and engineering applications. The NumPy array is similar to a list but where all the elements of the list are of the same type. The elements of a NumPy array, or simply an array, are usually numbers, but can also be booleans, strings, or other objects.

In [28]:
ba = array(aa)

NameError: name 'array' is not defined

In [29]:
import numpy as np
ba = np.array(aa)

In [30]:
ba

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
print (ba)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
print (len(aa))
print (ba.shape)

3
(3, 3)


Mathematical operations with arrays

In [33]:
ba + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
ba - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [35]:
ba * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [36]:
ba / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

## **Dictionary**

A Dictionary can be created by placing a sequence of elements within curly {} braces, separated by ‘comma’. Dictionary holds a pair of values, one being the Key and the other corresponding pair element being its Key:value. Values in a dictionary can be of any data type and can be duplicated, whereas keys can’t be repeated and must be immutable.

In [37]:
dic1 = {"a": 2, "b": 3, "c": 4}
print (dic1)

{'a': 2, 'b': 3, 'c': 4}


In [38]:
dic1["a"]

2

In [39]:
dic1[0]

KeyError: 0

In [48]:
dic1["a"][0]

TypeError: 'int' object is not subscriptable

In [43]:
dic1['c']

4

In [44]:
dic2 = {"col1": [1,2], "col2": (3, 4, 5), "col3": ["a", "b"], "col4": 5, "col5": 5., "col6": "last"}
print (dic2)

{'col1': [1, 2], 'col2': (3, 4, 5), 'col3': ['a', 'b'], 'col4': 5, 'col5': 5.0, 'col6': 'last'}


In [45]:
print (type(dic2["col1"]))
print (type(dic2["col2"]))
print (type(dic2["col3"]))
print (type(dic2["col4"]))
print (type(dic2["col5"]))
print (type(dic2["col6"]))

<class 'list'>
<class 'tuple'>
<class 'list'>
<class 'int'>
<class 'float'>
<class 'str'>


In [46]:
print (dic2['col1'][0])
print (dic2['col2'][2])
print (dic2['col3'][1])

1
5
b


## **Series and Data Frames**

Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively referred to as the index

In [49]:
import pandas as pd

In [50]:
d1 = {"a": 1, "b": 2, "c": 3}
print (d1)

{'a': 1, 'b': 2, 'c': 3}


In [51]:
s1 = pd.Series(d1)
print (s1)

a    1
b    2
c    3
dtype: int64


In [52]:
d2 = np.array([1, 2, 3])
print (d2)

[1 2 3]


In [53]:
s2 = pd.Series(d2, index=["a", "b", "c"])
print (s2)

a    1
b    2
c    3
dtype: int32


In [54]:
s1.shape

(3,)

In [55]:
s2.shape

(3,)

In [56]:
s1 == s2

a    True
b    True
c    True
dtype: bool

Pandas DataFrame is Two-dimensional, size-mutable, potentially heterogeneous tabular data. <br>
Data structure also contains labeled axes (rows and columns). Arithmetic operations align on both row and column labels. 

In [57]:
d3 = {'col1': [1, 2], 'col2': [3, 4]}
print (d3)

{'col1': [1, 2], 'col2': [3, 4]}


In [58]:
df1 = pd.DataFrame(data=d3)
print (df1)

   col1  col2
0     1     3
1     2     4


In [59]:
d4 = np.array([[1, 2, 3], [4, 5, 6], [7., 8., 9.]])
print (d4)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [60]:
df2 = pd.DataFrame(d4, columns=['col1', 'col2', 'col3'])
print (df2)

   col1  col2  col3
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0


In [61]:
print (df1['col1'])
print (df2['col1'])

0    1
1    2
Name: col1, dtype: int64
0    1.0
1    4.0
2    7.0
Name: col1, dtype: float64


In [62]:
df1.shape

(2, 2)

In [63]:
df2.shape

(3, 3)

In [64]:
df1 + 1

col1  col2
0     2     4
1     3     5

In [65]:
df2 * 2

col1  col2  col3
0   2.0   4.0   6.0
1   8.0  10.0  12.0
2  14.0  16.0  18.0

## **Functions**

A function is a group of related statements that performs a specific task. <br>
The Python interpreter has a number of functions and types built into it that are always available.

In [66]:
a = -3
b = 3
print (abs(a), abs(b))

3 3


In [67]:
max(a, b)

3

In [68]:
min(a, b)

-3

The four steps to defining a function in Python are the following:

1) Use the keyword def to declare the function and follow this up with the function name.
2) Add parameters to the function: they should be within the parentheses of the function. End your line with a colon.
3) Add statements that the functions should execute.
4) End your function with a return statement if the function should output something. Without the return statement, your function will return an object None

In [70]:
print_value(a)

-3


In [71]:
def print_value(x):
    print(x)

## **Conditional Execution**

Evaluate information and then choose one course of action or another based on the condition: conditional execution of a statement or group of statements based on the value of an expression.

In [72]:
x = 0
y = 5

In [73]:
if x < y:
    print('yes')

yes


In [74]:
if y < x:
    print('yes')
else:
    print('no')

no


In [75]:
if x:
    print('x')
elif y:
    print('y')
else:
    print('no')

y


In [76]:
if x or y:
    print('yes')

yes


In [77]:
if x and y:
    print('yes')

In [78]:
l = ['foo', 'bar', 'world']
if 'hello' in l:
    print('hello')
elif 'foo' in l:
    print('foo bar')    

foo bar


## **Loops**

A loop is a block of code that will repeat over and over again. There are two types of loops, **while loops** and **for loops**. While loops will repeat until a condition is no longer true, and for loops will repeat a certain number of times.

In [79]:
count = 0
while (count < 5):
    print(count, "Hello World!")
    count = count + 1

0 Hello World!
1 Hello World!
2 Hello World!
3 Hello World!
4 Hello World!


In [80]:
count = 0
while (count < 5):
    print(count, "Hello World")
    count += 1
else:
    print(count, "In Else Block")

0 Hello World
1 Hello World
2 Hello World
3 Hello World
4 Hello World
5 In Else Block


In [81]:
n = 5
for i in range(0, n):
    print(i)

0
1
2
3
4


In [82]:
l = ["a", "b", "c"]
for i in l:
    print(i)

a
b
c


In [83]:
t = ("a", "b", "c")
for i in t:
    print(i)

a
b
c


In [84]:
s = "Hello"
for i in s :
    print(i)

H
e
l
l
o


In [85]:
d = dict()
d['xyz'] = 123
d['abc'] = 345
for i in d :
    print("%s  %d" %(i, d[i]))

xyz  123
abc  345
