## **Arithmetic**

In [1]:
3 + 4

[1] 7

In [2]:
3 - 4

[1] -1

In [3]:
3 * 4

[1] 12

In [4]:
3 / 4

[1] 0.75

In [5]:
(2 + 3) * 4 / (2 - 3)

[1] -20

## **Variables and Assignments**

In [6]:
a <- 3
b <- 4
c = 3
d <- 3 + 2i
e <- "string"

In [7]:
print (a)
print (a,b,c)
print (c(a,b,c))
print (d)
print (e)

[1] 3
[1] 3
[1] 3 4 3
[1] 3+2i
[1] "string"


In [8]:
print (a + b)
print (a - b)
print (a * b)
print (a / b)

[1] 7
[1] -1
[1] 12
[1] 0.75


## **Logical Expression**

In [9]:
a <- 3
b <- -3
c <- 3

In [10]:
a == b

[1] FALSE

In [11]:
a != b

[1] TRUE

In [12]:
a > b

[1] TRUE

In [13]:
a < b

[1] FALSE

In [14]:
a <= b

[1] FALSE

In [15]:
(a == b) || (a > b)

[1] TRUE

In [16]:
(a !=b) && (a < b)

[1] FALSE

## **Vectors**

In [17]:
av <- c(1, 2, 3)
bv <- c("a", "b", "c")
cv <- c(1, 2, 3, "a", "b", "c")

In [18]:
print (av)
print (bv)
print (cv)

[1] 1 2 3
[1] "a" "b" "c"
[1] "1" "2" "3" "a" "b" "c"


In [19]:
print (av[0])
print (av[1])
print (bv[2])
print (cv[3])

numeric(0)
[1] 1
[1] "b"
[1] "3"


In [20]:
print (av)

[1] 1 2 3


In [21]:
av[1] <- 3
print (av)

[1] 3 2 3


In [22]:
bv[1] <- "new element"
print (bv)

[1] "new element" "b"           "c"          


## **Matrices**

Matrix in R is a table-like structure consisting of elements arranged in a fixed number of rows and columns. All the elements belong to a single data type. Elements of a matrix can be accessed by providing indexes of rows and columns

In [28]:
am <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow=3, ncol=3)
print (am)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [29]:
bm <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow=3, ncol=3, byrow=TRUE)
print (bm)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


## **Arrays**

Arrays are data storage objects in R containing more than or equal to 1 dimension. Arrays can contain only a single data type. The **array()** function is built-in function which takes input as avector and arranges them according to **dim** argument

In [30]:
av <- c(1, 2, 3)
bv <- c(4, 5, 6)
cv <- c(7, 8, 9)
print (av)
print (bv)
print (cv)

[1] 1 2 3
[1] 4 5 6
[1] 7 8 9


In [35]:
aa <- array(c(av, bv, cv), dim=c(3,3))

In [36]:
print (aa)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [37]:
rn <- c("first", "second", "third")
cn <- c("av", "bv", "cv")
ba <- array(c(av, bv, cv), dim=c(3,3), dimnames=list(rn, cn))

In [38]:
print (ba)

       av bv cv
first   1  4  7
second  2  5  8
third   3  6  9


In [39]:
ba + 2

av bv cv
first  3  6   9
second 4  7  10
third  5  8  11

In [40]:
ba - 2

av bv cv
first  -1 2  5 
second  0 3  6 
third   1 4  7

In [41]:
ba * 2

av bv cv
first  2   8 14
second 4  10 16
third  6  12 18

In [42]:
ba / 2

av  bv  cv 
first  0.5 2.0 3.5
second 1.0 2.5 4.0
third  1.5 3.0 4.5

## **Data Frames**

A data frame is used for storing data tables. It is a list of vectors of equal length

In [43]:
a = c(1, 2, 3) 
b = c("aa", "bb", "cc") 
c = c(TRUE, FALSE, TRUE) 
df = data.frame(a, b, c)

In [44]:
print (df)

  a  b     c
1 1 aa  TRUE
2 2 bb FALSE
3 3 cc  TRUE


In [45]:
df[1]

a
1 1
2 2
3 3

In [46]:
df['c']

c    
1  TRUE
2 FALSE
3  TRUE

In [47]:
df[1:2]

a b 
1 1 aa
2 2 bb
3 3 cc

In [48]:
df[1:2,]

a b  c    
1 1 aa  TRUE
2 2 bb FALSE

In [49]:
print (df$a)
print (df$c)
print (df$b)

[1] 1 2 3
[1]  TRUE FALSE  TRUE
[1] "aa" "bb" "cc"


In [50]:
print (df$a[2])
print (df$b[3])
print (df$c[1])

[1] 2
[1] "cc"
[1] TRUE


## **Functions**

A function is a group of related statements that performs a specific task. <br>
The R interpreter has a number of functions and types built into it that are always available.

In [51]:
a <- -3
b <- 3
print (c(abs(a), abs(b)))

[1] 3 3


In [52]:
max(a, b)

[1] 3

In [53]:
min(a, b)

[1] -3

The five steps to defining a function in Python are the following:

1) Declare the function name and follow with the keyword *function*.
2) Add parameters to the function: they should be within the parentheses of the function. End your line with a left curly bracket.
3) Add statements that the functions should execute.
4) End your function with a return statement if the function should output something. Without the return statement, your function will return an object None
5) End your function with a right curly bracket.

In [54]:
print_value <- function(x) {
    print(x)
}

In [56]:
print_value(a)

[1] -3


## **Conditional Execution**

Evaluate information and then choose one course of action or another based on the condition: conditional execution of a statement or group of statements based on the value of an expression.

In [57]:
x <- 0
y <- 5

In [58]:
if (x < y) {
    print('yes')
}

[1] "yes"


In [59]:
if (y < x) {
    print('yes')
} else {
    print('no')
}

[1] "no"


In [60]:
if (x) {
    print('x')
} else if (y) {
    print('y')
} else {
    print('no')
}

[1] "y"


In [61]:
if (x | y) {
    print('yes')
}

[1] "yes"


In [62]:
if (x & y) {
    print('yes')
}

In [63]:
l <- c('foo', 'bar', 'world')
if ('hello' %in% l) {
    print('hello')
} else if ('foo' %in% l) {
    print('foo bar')
}

[1] "foo bar"


## **Loops**

A loop is a block of code that will repeat over and over again. There are two types of loops, **while loops** and **for loops**. While loops will repeat until a condition is no longer true, and for loops will repeat a certain number of times.

In [64]:
count <- 0
while (count < 5) {
    print(c(count, "Hello World!"))
    count <- count + 1
}

[1] "0"            "Hello World!"
[1] "1"            "Hello World!"
[1] "2"            "Hello World!"
[1] "3"            "Hello World!"
[1] "4"            "Hello World!"


In [65]:
n = 5
for (i in 1:n) {
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [66]:
l <- c("a", "b", "c")
for (i in l) {
    print(i)
}

[1] "a"
[1] "b"
[1] "c"


In [67]:
s = "Hello"
for (i in s) {
    print(i)
}

[1] "Hello"
