# **Numerical Analysis**

*Numerical analysis* involves the study, development, and analysis of algorithms for obtaining numerical solutions to various mathematical problems. Frequently, numerical analysis is so called mathematics of scientific computing.

Numerical analysis covers:
   - Solving of linear or nonlinear equations
   - Numerical linear algebra
   - Approximating functions
   - Numerical differentiation
   - Numerical integration
   - Solving of ODE and PDE
   - Optimization
   - and so on

Today's class will cover only numerical differentiation and integration methods.

Let $D_{n}$ be a set of $n+1$ given points in the $(x, y)$ plane:

$$
D_{n} = {(x_i, y_i) | 0 \le i \le n; a = x_0 < x-1 < ...< x_n = b; y_i = f(x_{i})}
$$

for some function $f(x)$. <br><br>
We are seeking to find accurate *approximations* for: <br>
1. $f^{\prime}(x_{i})$ and/or $f^{\prime\prime}(x_{i})$: $i = 0, 1, ..., n$ (*Numerical Differentiation*), <br>
2. $I = \int^{b}_{a} f(x) dx$ (Numerical Integration).

## Mathematical Prerequisites

### **Taylor's formula**

Let $h_0 > 0$ and $m \in {\rm I\!R}$. Assume that the function $f(x) \in C^{k+1}[(m-h_0, m+h_0)]$ that is, its derivatives

$$
{f^{(j)} (x) : j =1, ..., k, k+1}
$$

are continuous in the interval $(m-h_0, m+h_0)$. Then for all $h < h_0 \in {\rm I\!R}$, there exists $t \in (0, 1)$, such that:

$$f(m+h) = f(m) + f^{\prime}(m)h + f^{(2)}(m) \frac{h^2}{2} + ... + f^{(k)}(m) \frac{h^{k}}{k!} + f^{(k+1)}(c) \frac{h^{k+1}}{(k+1)!}
$$

with $c = m + th$.<br>
We can abbreviate the formula as follows:

$$
f(m+h) = f(m) + f^{\prime}(m)h + f^{(2)}(m) \frac{h^2}{2} + ... + f^{(k)}(m) \frac{h^{k}}{k!} + O(h^{k+1})
$$

For the cas where $f$ is analytic, then

$$
f(m+h) = f(m) + f^{\prime}(m)h + f^{(2)}(m) \frac{h^2}{2} + ... + f^{(k)}(m) \frac{h^{k}}{k!} + ... = \sum^{\infty}_{n=0} f^{(n)}(m) \frac{h^{n}}{n!}
$$

Evaluation of $e^x$ for an arbitrary $x$.

$$
e^{x} = \sum^{\infty}_{n=0} \frac{x^n}{n!}
$$

In [1]:
import math

x = 2
exact_f = math.exp(x)
print (exact_f)

7.38905609893065


In [2]:
def exp_x(y, n):
    ret = 0
    for i in range(0, n):
        ret += y**i / math.factorial(i)
    return ret

In [3]:
approx_f = exp_x(x, 100)
print (approx_f)

7.389056098930649


In [4]:
for i in range(1, 20):
    approx_f = exp_x(x, i)
    error_f = abs(approx_f - exact_f)
    print (f'{i}th terms: Taylor Series approx= {approx_f}, exact= {exact_f}, error = {error_f}')    

1th terms: Taylor Series approx= 1.0, exact= 7.38905609893065, error = 6.38905609893065
2th terms: Taylor Series approx= 3.0, exact= 7.38905609893065, error = 4.38905609893065
3th terms: Taylor Series approx= 5.0, exact= 7.38905609893065, error = 2.3890560989306504
4th terms: Taylor Series approx= 6.333333333333333, exact= 7.38905609893065, error = 1.0557227655973174
5th terms: Taylor Series approx= 7.0, exact= 7.38905609893065, error = 0.3890560989306504
6th terms: Taylor Series approx= 7.266666666666667, exact= 7.38905609893065, error = 0.1223894322639838
7th terms: Taylor Series approx= 7.355555555555555, exact= 7.38905609893065, error = 0.033500543375095226
8th terms: Taylor Series approx= 7.3809523809523805, exact= 7.38905609893065, error = 0.00810371797826992
9th terms: Taylor Series approx= 7.387301587301587, exact= 7.38905609893065, error = 0.0017545116290635931
10th terms: Taylor Series approx= 7.3887125220458545, exact= 7.38905609893065, error = 0.0003435768847959153
11th ter

### **Intermediate value theorem**

The *intermediate value theorem* states that if $f$ is a continuous function whose domain contains the interval $[a, b]$, then it takes on any given value between $f(a)$ and $f(b)$ at some point within the interval.
- If a continuous function has values of opposite sign inside an interval, then it has a root in that interval (Bolzano's theorem).

### **Mean value theorm**

*Mean value theorem* results from the application of Taylor's formula where the error term is expressed in terms of a first derivative, specifically:

$$
f(m + h) - f(m) = hf^{\prime}(c); c \in (m, m + h);
$$

which is equivalent to:

$$
\int^{m+h}_{m} f^{\prime}(x)dx = f^{\prime}(c) h
$$

## Numerical Differentiation

### **Approximation of first derivatives**

***1) The forward divided difference approximation***

Using Taylor's formula up to order 1,

$$
f(x+h) = f(x) + h f^{\prime}(x) + \frac{1}{2} h^2 f^{\prime\prime}(c)
$$
where $c$ is in ther interval $(x, x+h)$, then

$$
f^{\prime} (x) = \frac{1}{h} \left[ f(x+h) - f(x) \right] - \frac{1}{2} h^2 f^{\prime\prime}(c)
$$

Therefore, the approximation

$$f^{\prime} (x) \approx \frac{1}{h} \left[ f(x+h) - f(x) \right]
$$

is the first order *forward divided difference approximation* with a truncation error term $-\frac{1}{2} h^2 f^{\prime\prime}(c)$ of order $h$.


***2) The backward divided difference approximation***

Likewise, replacing $h$ by $-h$,,

$$
f(x-h) = f(x) - h f^{\prime}(x) + \frac{1}{2} h^2 f^{\prime\prime}(c)
$$

where $c$ is in ther interval $(x-h, x)$, then

$$
f^{\prime} (x) = \frac{1}{h} \left[ f(x) - f(x-h) \right] + \frac{1}{2} h^2 f^{\prime\prime}(c)
$$

Therefore, the approximation

$$
f^{\prime} (x) \approx \frac{1}{h} \left[ f(x) - f(x-h) \right]
$$

is the first order *backward divided difference approximation* with a truncation error term $+\frac{1}{2} h^2 f^{\prime\prime}(c)$ of order $h$.

***3)The central difference approximation***

Using Taylor's formula up to order 3,

$$
f(x+h) = f(x) + h f^{\prime}(x) + \frac{1}{2!} h^2 f^{(2)}(x) + \frac{1}{3!} h^3 f^{(3)}(c_1)
$$

where $c_1$ is in the interval $(x, x+h)$, and similarly

$$
f(x-h) = f(x) - h f^{\prime}(x) + \frac{1}{2!} h^2 f^{(2)}(x) - \frac{1}{3!} h^3 f^{(3)}(c_2)
$$

where $c_2$ is in the interval $(x-h, x)$.<br>
By substraction, and using the intermediate value theorem,

$$
$f(x+h) - f(x-h) = 2hf^{\prime}(x) + \frac{2}{3!} h^3 f^{(3)} (c)
$$

This leads to a new approximation for $f^{\prime}(x)$:

$$f^{\prime} (x) \approx \frac{1}{2h} \left[ f(x+h) - f(x-h) \right] - \frac{1}{3!} h^2 f^{(3)} (c)
$$

where the approximation

$$
f^{\prime} (x) \approx \frac{ \left[ f(x+h) - f(x-h) \right]}{2h}
$$

is the first order *central difference approximation* to $f^{\prime}(x)$, with its truncation error $O(h^2)$.

In [7]:
import numpy as np

def f(x):
    return (x*x*x)

def fprime(x):
    return (3*x*x)

xval = np.array([1, 2, 3, 4, 5])
fval = f(xval)
fprimeval = fprime(xval)
print (xval)
print (fval)
print (fprimeval)

[1 2 3 4 5]
[  1   8  27  64 125]
[ 3 12 27 48 75]


In [8]:
from scipy.misc import derivative

dev = derivative(f, xval, dx=0.01, n=1)
err = dev - fprimeval
err_mean = np.mean(err)
err_std = np.std(err)
print (dev)
print (err)
print (err_mean, err_std)

[ 3.0001 12.0001 27.0001 48.0001 75.0001]
[1.00000000e-04 9.99999998e-05 9.99999995e-05 9.99999987e-05
 9.99999983e-05]
9.999999928496095e-05 6.509378139315772e-13


In [9]:
def numerical_derivative_first(g,a,method='central',h=0.01):
    '''
    Difference formula:
    forward: g(a+h) - g(a))/h
    backward: g(a) - g(a-h))/h            
    central: g(a+h) - g(a-h))/(2*h)
    '''
    if method == 'forward':
        return (g(a + h) - g(a))/h
    elif method == 'backward':
        return (g(a) - g(a - h))/h
    elif method == 'central':
        return (g(a + h) - g(a - h))/(2*h)
    else:
        raise ValueError("Method must be 'central', 'forward' or 'backward'.")

In [10]:
dev_forward = numerical_derivative_first(f, xval, method="forward", h=0.001)
err1 = dev_forward - fprimeval
err1_mean = np.mean(err1)
err1_std = np.std(err1)
print (dev_forward)
print (err1)
print (err1_mean, err1_std)

[ 3.003001 12.006001 27.009001 48.012001 75.015001]
[0.003001 0.006001 0.009001 0.012001 0.015001]
0.009001000007698323 0.004242640697029869


In [11]:
dev_backward = numerical_derivative_first(f, xval, method="backward", h=0.1)
err2 = dev_backward - fprimeval
err2_mean = np.mean(err2)
err2_std = np.std(err2)
print (dev_backward)
print (err2)
print (err2_mean, err2_std)

[ 2.71 11.41 26.11 46.81 73.51]
[-0.29 -0.59 -0.89 -1.19 -1.49]
-0.8900000000000468 0.4242640687120061


In [12]:
dev_central = numerical_derivative_first(f, xval, method="central", h=0.01)
err3 = dev_central - fprimeval
err3_mean = np.mean(err3)
err3_std = np.std(err3)
print (dev_central)
print (err3)
print (err3_mean, err3_std)

[ 3.0001 12.0001 27.0001 48.0001 75.0001]
[1.00000000e-04 9.99999998e-05 9.99999995e-05 9.99999987e-05
 9.99999983e-05]
9.999999928496095e-05 6.509378139315772e-13


### **Approximation of second derivatives**

***1) The forward divided difference approximation***

Consider the 2 Taylor's series expansions of $f$ up to second order given by:

$$
f(x+h) = f(x) + h f^{\prime}(x) + \frac{1}{2!} h^2 f^{\prime\prime}(x) + \frac{1}{3!} h^3 f^{(3)} (c_1); c_1 \in (x, x+h)
$$

$$
f(x+2h) = f(x) + (2h) f^{\prime}(x) + \frac{1}{2!} (2h)^2 f^{\prime\prime} (x) + \frac{1}{3!} (2h)^3 f^{(3)} (c_2); c_2 \in (x, x+2h)
$$

where f is assumed to be a $C^{3}$-function.<br>
Then, the algebraic operation, $f(x+2h) - 2f(x+h)$ leads to the forward difference approximation to $f^{\prime\prime}(x)$, which satisfies the following:

$$
f^{\prime\prime}(x) = \frac{f(x+2h) - 2f(x+h) + f(x)}{h^{2}} + O(h)
$$

***2) The backward divided difference approximation***

Replacing $h$ by $-h$,,

$$
f(x+h) = f(x) - h f^{\prime}(x) + \frac{1}{2!} h^2 f^{\prime\prime}(x) - \frac{1}{3!} h^3 f^{(3)} (c_1); c_1 \in (x-h, x)
$$

$$
f(x-2h) = f(x) - (2h) f^{\prime}(x) + \frac{1}{2!} (2h)^2 f^{\prime\prime} (x) - \frac{1}{3!} (2h)^3 f^{(3)} (c_2); c_2 \in (x-2h, x)
$$

Then, the algebraic operation, $f(x-2h) - 2f(x-h)$ leads to the forward difference approximation to $f^{\prime\prime}(x)$, which satisfies the following:

$$
f^{\prime\prime}(x) = \frac{f(x-2h) - 2f(x-h) + f(x)}{h^{2}} + O(h)
$$

***3)The central difference approximation***

Using Taylor's formula up to order 3,

$$
f(x+h) = f(x) + h f^{\prime}(x) + \frac{1}{2!} h^2 f^{(2)}(x) + \frac{1}{3!} h^3 f^{(3)} (x) + \frac{1}{4!} h^4 f^{(4)} (c_1); c_1 \in (x, x+h)
$$

$$
f(x-h) = f(x) - h f^{\prime}(x) + \frac{1}{2!} h^2 f^{(2)}(x) - \frac{1}{3!} h^3 f^{(3)} (x) + \frac{1}{4!} h^4 f^{(4)} (c_2); c_2 \in (x-h, x)
$$

By addition,

$$
f(x+h) + f(x-h) = 2hf(x) + f^{\prime\prime}(x)h^2 + \frac{1}{4!} h^4 \left(f^{(4)} (c_1)+f^{(4)} (c_2) \right)
$$

Dividing by $h^2$ and using the intermdiate value theorem, one conclude that:

$$
f^{\prime\prime} (x) \approx \frac{ \left[ f(x+h) - 2f(x) + f(x-h) \right]}{h^2} + O(h^2)
$$

which is the *central difference approximation* to $f^{\prime\prime}$.

In [13]:
def fdoubleprime(x):
    return (6*x)

fdoubleprimeval = fdoubleprime(xval)
print (fdoubleprimeval)

[ 6 12 18 24 30]


In [14]:
dev2 = derivative(f, xval, dx=0.1, n=2)
err = dev2 - fdoubleprimeval
err_mean = np.mean(err)
err_std = np.std(err)
print (dev2)
print (err)
print (err_mean, err_std)

[ 6. 12. 18. 24. 30.]
[ 4.88498131e-14 -7.99360578e-14  3.23296945e-13 -1.93622895e-12
  1.12976295e-12]
-1.028510610012745e-13 1.0085387624844923e-12


In [15]:
def numerical_derivative_second(g,a,method='central',h=0.01):
    '''
    Difference formula:
    forward: (g(a+2*h) - 2*g(a+h) + g(a))/h**2
    backward: (g(a-2*h) - 2*g(a-h) + g(a))/h**2
    central: (g(a+h) - 2*g(x) + g(a-h))/h**2
    '''
    if method == 'forward':
        return (g(a+2*h) - 2*g(a+h) + g(a))/h**2
    elif method == 'backward':
        return (g(a-2*h) - 2*g(a-h) + g(a))/h**2
    elif method == 'central':
        return (g(a+h) - 2*g(a) + g(a-h))/h**2
    else:
        raise ValueError("Method must be 'central', 'forward' or 'backward'.")

In [16]:
dev2_forward = numerical_derivative_second(f, xval, method="forward", h=1e-6)
err4 = dev2_forward - fdoubleprimeval
err4_mean = np.mean(err4)
err4_std = np.std(err4)
print (dev2_forward)
print (err4)
print (err4_mean, err4_std)

[ 6.0005334  11.99396138 17.98383664 24.01634447 29.98490345]
[ 0.0005334  -0.00603862 -0.01616336  0.01634447 -0.01509655]
-0.0040841314039425924 0.011913441603633569


In [17]:
dev2_backward = numerical_derivative_second(f, xval, method="backward", h=1e-6)
err5 = dev2_backward - fdoubleprimeval
err5_mean = np.mean(err5)
err5_std = np.std(err5)
print (dev2_backward)
print (err5)
print (err5_mean, err5_std)

[ 6.0005334  11.99573774 18.01225835 24.0234499  30.01332516]
[ 0.0005334  -0.00426226  0.01225835  0.0234499   0.01332516]
0.009060909207619261 0.009855715978367218


In [18]:
dev2_central = numerical_derivative_second(f, xval, method="central", h=0.1)
err6 = dev2_central - fdoubleprimeval
err6_mean = np.mean(err6)
err6_std = np.std(err6)
print (dev2_central)
print (err6)
print (err6_mean, err6_std)

[ 6. 12. 18. 24. 30.]
[ 4.88498131e-14  8.88178420e-15  3.23296945e-13 -1.22568622e-12
  1.12976295e-12]
5.702105454474804e-14 7.57548695767607e-13


## **2. Numerical Integration**

### **The trapezoidal rule**

A simple geometric argument consists in approximating the surface between the $x$-axis, the curve $y = f(x)$ and the vertical lines $x = x_k$ and $x = x_{k+1}$ by the area of the rectangular trapezoid which vertices are $(x_k, 0)$, $(x_{k+1}, 0)$, $(x_k, f(x_k))$ and $(x_{k+1}. f(x_{k+1}))$. This leads first to the simple trapezoidal rule, given by:<br>

$$
g = \int^{x_{k+1}}_{x_k} f(x)dx \approx T_k = \frac{h}{2} (f(x_k) + f(x_{k+1}))
$$

and subsequently to the composite trapezoid rule given by:<br>

$$
I = I(a,b) = \int^{b}_{a} f(x) dx \approx T(h) = \frac{h}{2} \sum^{n-1}_{k=0} \left( f(x_k) + f(x_{k+1}) \right)
$$

An error of the trapezoidal rule can be derived to:

$$
I = I(a,b) = T(h) - \frac{(b-a)}{12} f^{\prime\prime}(c) h^2; c \in (a,b)
$$

In [19]:
def trap(func, a, b, n):
    h = (b-a) / n
    int_val = 0.5 * h * (func(a) + func(b))
    for i in range(0, int(n)):
        int_val = int_val + h * func(i * h)
    return int_val

In [20]:
def f(x):
    return (x ** 2)

neval = 10
for i in range(1, neval):
    print (trap(f, 0, 1, i))

0.5
0.375
0.35185185185185186
0.34375
0.3400000000000001
0.3379629629629629
0.33673469387755095
0.3359375
0.3353909465020576


In [21]:
print (trap(f, 0, 1, 100))

0.33335000000000015


### **Simpson's rule**

Simpson’s rule is applicable only if the number of subintervals is even. Its accuracy is higher  than the trapezoid rule. The simple Simpson’s rule is defined as:

$$
S_k = \frac{h}{3} \left[ f(x_{2k}) + 4 f(x_{2k+1}) + f(x_{2k+2}) \right]
$$

Then the composite Simpson's rule can be derived into:

$$
I = I(a,b) = \frac{h}{3} \sum^{m-1}_{k=0} \left[ f(x_{2k} + 4 f(x_{2k+1}) + f(x_{2k+2}) \right] -\frac{(b-a)h^{4}}{180} f^{(4)}(c)
$$

In [22]:
def simps(func,a,b,n=100):
    if n % 2 == 1:
        raise ValueError("N must be an even integer.")
    dx = (b-a)/float(n)
    xi = np.linspace(a,b,n+1)
    yi = func(xi)
    S = dx/3 * np.sum(yi[0:-1:2] + 4*yi[1::2] + yi[2::2])
    return S

In [23]:
neval = 4
print (simps(f, 0, 1, neval))

0.3333333333333333
